# Base Wordlists:

main_wordlist="~/.config/content/wordlists/raft-medium-words.txt"
small_wordlist="~/.config/content/wordlists/raft-medium-words.txt"

# Technology Specific Wordlists:

Java="~/.config/content/wordlists/Java.txt"
Python="~/.config/content/wordlists/Python"
Go="~/.config/content/wordlists/GO.txt"
JBoss_Web="~/.config/content/wordlists/Jboss.txt"
JBoss_Application_Server="~/.config/content/wordlists/Jboss.txt"
PHP="~/.config/content/wordlists/PHP.txt"
Laravel="~/.config/content/wordlists/Laravel.txt"
Atlassian_Confluence="~/.config/content/wordlists/Confluence.txt"
Microsoft_ASP_NET="~/.config/content/wordlists/IIS-ASP.txt"
Nginx="~/.config/content/wordlists/nginx.txt"
Ruby_on_Rails="~/.config/content/wordlists/ror.txt"
Spring="~/.config/content/wordlists/Spring.txt"
Oracle_BlueKai="~/.config/content/wordlists/oracle.txt"
Oracle_Commerce="~/.config/content/wordlists/oracle.txt"
Oracle_Commerce_Cloud="~/.config/content/wordlists/oracle.txt"
Oracle_Dynamic_Monitoring_Service="~/.config/content/wordlists/oracle.txt"
Oracle_HTTP_Server="~/.config/content/wordlists/oracle.txt"
Oracle_Infinity="~/.config/content/wordlists/oracle.txt"
Oracle_Maxymiser="~/.config/content/wordlists/oracle.txt"
Oracle_Recommendations_On_Demand="~/.config/content/wordlists/oracle.txt"
Oracle_Web_Cache="~/.config/content/wordlists/oracle.txt"
Adobe_Experience_Manager="~/.config/content/wordlists/AEM.txt"
Apache="~/.config/content/wordlists/Apache.txt"
Apache_Tomcat="~/.config/content/wordlists/ApacheTomcat.txt"
CFML="~/.config/content/wordlists/ColdFusion.txt"
Django="~/.config/content/wordlists/Django.txt"
Drupal="~/.config/content/wordlists/Drupal.txt"
SAP="~/.config/content/wordlists/SAP.txt"
Microsoft_SharePoint="~/.config/content/wordlists/Sharepoint.txt"
SiteMinder="~/.config/content/wordlists/SiteMinder.txt"
Sitefinity="~/.config/content/wordlists/Sitefinity.txt"
Umbraco="~/.config/content/wordlists/umbraco.txt"
Flyspray="~/.config/content/wordlists/Flyspray.txt"
Joomla="~/.config/content/wordlists/Joommla.txt"
Kentico_CMS="~/.config/content/wordlists/Kentico.txt"
MODX="~/.config/content/wordlists/MODX.txt"
PHP_Nuke="~/.config/content/wordlists/PHP-Nuke.txt"
Matomo_Analytics="~/.config/content/wordlists/Matomo.txt"
Shopware="~/.config/content/wordlists/Shopware.txt"
Sitecore="~/.config/content/wordlists/Sitecore.txt"
Magento="~/.config/content/wordlists/Magento.txt"
Symfony="~/.config/content/wordlists/Symfony.txt"
Wordpress="~/.config/content/wordlists/Wordpress.txt"
FrontPage="~/.config/content/wordlists/Frontpage.txt"
Jenkins="~/.config/content/wordlists/Jenkins.txt"
RoundCube="~/.config/content/wordlists/RoundCube.txt"
GlassFish="~/.config/content/wordlists/GlassFish.txt"
Lotus_Domino="~/.config/content/wordlists/Lotus.txt"
Oracle_Application_Server="~/.config/content/wordlists/OracleAppServer.txt"
Node_js="~/.config/content/wordlists/Nodejs.txt"
