# Base Wordlists:

main_wordlist="~/.config/chameleon/wordlists/raft-medium-words.txt"
small_wordlist="~/.config/chameleon/wordlists/raft-medium-words.txt"

# Technology Specific Wordlists:

Flask="~/.config/chameleon/wordlists/Flask.txt"
Java="~/.config/chameleon/wordlists/Java.txt"
#Python="~/.config/chameleon/wordlists/Python"
Go="~/.config/chameleon/wordlists/GO.txt"
JBoss_Web="~/.config/chameleon/wordlists/Jboss.txt"
JBoss_Application_Server="~/.config/chameleon/wordlists/Jboss.txt"
PHP="~/.config/chameleon/wordlists/PHP.txt"
Laravel="~/.config/chameleon/wordlists/Laravel.txt"
Atlassian_Confluence="~/.config/chameleon/wordlists/Confluence.txt"
Microsoft_ASP_NET="~/.config/chameleon/wordlists/IIS-ASP.txt"
Nginx="~/.config/chameleon/wordlists/nginx.txt"
Ruby_on_Rails="~/.config/chameleon/wordlists/ror.txt"
Spring="~/.config/chameleon/wordlists/Spring.txt"
Oracle_BlueKai="~/.config/chameleon/wordlists/oracle.txt"
Oracle_Commerce="~/.config/chameleon/wordlists/oracle.txt"
Oracle_Commerce_Cloud="~/.config/chameleon/wordlists/oracle.txt"
Oracle_Dynamic_Monitoring_Service="~/.config/chameleon/wordlists/oracle.txt"
Oracle_HTTP_Server="~/.config/chameleon/wordlists/oracle.txt"
Oracle_Infinity="~/.config/chameleon/wordlists/oracle.txt"
Oracle_Maxymiser="~/.config/chameleon/wordlists/oracle.txt"
Oracle_Recommendations_On_Demand="~/.config/chameleon/wordlists/oracle.txt"
Oracle_Web_Cache="~/.config/chameleon/wordlists/oracle.txt"
Adobe_Experience_Manager="~/.config/chameleon/wordlists/AEM.txt"
Apache="~/.config/chameleon/wordlists/Apache.txt"
Apache_Tomcat="~/.config/chameleon/wordlists/ApacheTomcat.txt"
CFML="~/.config/chameleon/wordlists/ColdFusion.txt"
Django="~/.config/chameleon/wordlists/Django.txt"
Drupal="~/.config/chameleon/wordlists/Drupal.txt"
SAP="~/.config/chameleon/wordlists/SAP.txt"
Microsoft_SharePoint="~/.config/chameleon/wordlists/Sharepoint.txt"
SiteMinder="~/.config/chameleon/wordlists/SiteMinder.txt"
Sitefinity="~/.config/chameleon/wordlists/Sitefinity.txt"
Umbraco="~/.config/chameleon/wordlists/umbraco.txt"
Flyspray="~/.config/chameleon/wordlists/Flyspray.txt"
Joomla="~/.config/chameleon/wordlists/Joommla.txt"
Kentico_CMS="~/.config/chameleon/wordlists/Kentico.txt"
MODX="~/.config/chameleon/wordlists/MODX.txt"
PHP_Nuke="~/.config/chameleon/wordlists/PHP-Nuke.txt"
Matomo_Analytics="~/.config/chameleon/wordlists/Matomo.txt"
Shopware="~/.config/chameleon/wordlists/Shopware.txt"
Sitecore="~/.config/chameleon/wordlists/Sitecore.txt"
Magento="~/.config/chameleon/wordlists/Magento.txt"
Symfony="~/.config/chameleon/wordlists/Symfony.txt"
WordPress="~/.config/chameleon/wordlists/Wordpress.txt"
FrontPage="~/.config/chameleon/wordlists/Frontpage.txt"
Jenkins="~/.config/chameleon/wordlists/Jenkins.txt"
RoundCube="~/.config/chameleon/wordlists/RoundCube.txt"
GlassFish="~/.config/chameleon/wordlists/GlassFish.txt"
Lotus_Domino="~/.config/chameleon/wordlists/Lotus.txt"
Oracle_Application_Server="~/.config/chameleon/wordlists/OracleAppServer.txt"

# Technology specific Extensions

Microsoft_ASP_NET_ext="aspx,ashx,asmx,asp"
Java_ext="jsp"
CFML_ext="cfm"
Python_ext="py"
PHP_ext="php"
